language: node_js
node_js:
  - "10.0"
  - "11.0"
  - "12.0"
  - "13.0"
  - "14.8"
  - "16.13"
sudo: true
cache:
  directories:
    - node_modules
before_script:
  - npm install
branches:
  only:
    - master
